#+title:  Telegram-Weather-and-Counting-bot-who-speaks-Spanish
#+author: Na_P

** Introduction
Telegram bot made with Python using [[https://docs.python-telegram-bot.org/en/stable/][python-telegram-bot]]. \\
Currently can check the weather and has a pretty counter with two buttons.

** How to run
Needs a config.toml file in the same dir as [[file:src/main.py][main.py]] containing the fields BOT_TOKEN (your bot token) and WEATHER_API_KEY (your [[https://openweathermap.org/api][OpenWeatherMap API]] key). \\
Obviously needs Python too (Python 3.10 was used to make this).

** Commands
| Name    | Description                 |
|---------+-----------------------------|
| /start  | Comenzar bot                |
| /clima  | Consultar el clima          |
| /contar | Crear un nuevo contador     |
| /no     | Regresar al menu principal  |
| /cease  | Borrar datos de usuario     |

** Files
*** [[file:src/main.py][src/main.py]]
Here's the bot. \\
that's

*** [[file:src/requirements.py][src/requirements.txt]]
Dependencies for this bot.

*** [[file:setup.py][setup.py]]
Utility script to set up a venv with the [[file:src/requirements.txt][requirements]] to run this bot. \\
If you want to do it yourself, you're free to.

*** [[file:run.py][run.py]]
Utility script to run the bot using the venv created by [[file:setup.py][setup.py]]. \\
You can also do this yourself!

